// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xcygyqegomdgtmovkwac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhjeWd5cWVnb21kZ3Rtb3Zrd2FjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDUxMTIsImV4cCI6MjA2NDI4MTExMn0.lZlldr9zvVMCUxo2MbxQRRFl_iUwJUZFr_LUA6uriWw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);